---
micronaut:
  application:
    name: issueManager

---
datasources:
  default:
    url: jdbc:postgresql://postgres:5432/sicred
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES

---
jpa:
  default:
    packages-to-scan:
      - "com.leo.entity"
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

---
netty:
  default:
    allocator:
      max-order: 3
